### ISSUE TITLE
unifycr_init_structures initializes all existing files as 'not in_use'

### ISSUE THREAD

**Issue by sandrain** [LLNL/UnifyCR#164]
When unifycr is initializing, it blindly initializes all entries in `unifycr_filelist` array as not in use (`in_use = 0`), which leads to a failure of opening an existing file.

The following is the trace when the file system is re-mounted in the client, after running sysio-write.

```
(gdb) b unifycr_init_structures
Breakpoint 1 at 0x409753: file ../../../../client/src/unifycr.c, line 1325.
(gdb) b __wrap_open
Breakpoint 2 at 0x405168: file ../../../../client/src/unifycr-sysio.c, line 681.
(gdb) c
Continuing.

Breakpoint 1, unifycr_init_structures () at ../../../../client/src/unifycr.c:1325
1325        for (i = 0; i < unifycr_max_files; i++) {
(gdb) bt
#0  unifycr_init_structures () at ../../../../client/src/unifycr.c:1325
#1  0x0000000000409b46 in unifycr_superblock_shmget (size=1040350308, key=0) at ../../../../client/src/unifycr.c:1424
#2  0x000000000040a25e in unifycr_init (rank=0) at ../../../../client/src/unifycr.c:1725
#3  0x000000000040c120 in unifycrfs_mount (prefix=0x416f33 "/tmp", size=1, rank=0) at ../../../../client/src/unifycr.c:2517
#4  0x000000000040a653 in unifycr_mount (prefix=0x416f33 "/tmp", rank=0, size=1, l_app_id=0) at ../../../../client/src/unifycr.c:1837
#5  0x0000000000403d7e in main (argc=1, argv=0x7fffffffdbc8) at ../../../../examples/src/sysio-read.c:371
(gdb) p unifycr_filelist[0]
$1 = {in_use = 1, filename = "/tmp", '\000' <repeats 1019 times>}
(gdb) p unifycr_filelist[1]                                                                                                                         
$2 = {in_use = 1, filename = "/tmp/testfile", '\000' <repeats 1010 times>}
(gdb) l
1320
1321    /* initialize data structures for first use */
1322    static int unifycr_init_structures()
1323    {
1324        int i;
1325        for (i = 0; i < unifycr_max_files; i++) {
1326            /* indicate that file id is not in use by setting flag to 0 */
1327            unifycr_filelist[i].in_use = 0;
1328
1329            /* set pointer to array of chunkmeta data structures */
(gdb) l
1330            unifycr_filemeta_t *filemeta = &unifycr_filemetas[i];
1331
1332            unifycr_chunkmeta_t *chunkmetas;
1333            if (!unifycr_use_spillover) {
1334                chunkmetas = &(unifycr_chunkmetas[unifycr_max_chunks * i]);
1335            } else
1336                chunkmetas = &(unifycr_chunkmetas[(unifycr_max_chunks +
1337                                                   unifycr_spillover_max_chunks) * i]);
1338            filemeta->chunk_meta = chunkmetas;
1339        }
(gdb) b 1340
Breakpoint 3 at 0x40982f: file ../../../../client/src/unifycr.c, line 1340.
(gdb) c
Continuing.

Breakpoint 3, unifycr_init_structures () at ../../../../client/src/unifycr.c:1341
1341        unifycr_stack_init(free_fid_stack, unifycr_max_files);
(gdb) p unifycr_filelist[0]
$3 = {in_use = 0, filename = "/tmp", '\000' <repeats 1019 times>}
(gdb) p unifycr_filelist[1]                                                                                                                         
$4 = {in_use = 0, filename = "/tmp/testfile", '\000' <repeats 1010 times>}
(gdb) c
Continuing.

Breakpoint 2, __wrap_open (path=0x61d640 <targetfile> "/tmp/testfile", flags=0) at ../../../../client/src/unifycr-sysio.c:681
681         int mode = 0;

(gdb) 
456         while (i < unifycr_max_files) {
(gdb) 
457             if (unifycr_filelist[i].in_use &&
(gdb) 
463             i++;
(gdb) l
458                 strcmp((void *)&unifycr_filelist[i].filename, path) == 0) {
459                 DEBUG("File found: unifycr_filelist[%d].filename = %s\n",
460                       i, (char *)&unifycr_filelist[i].filename);
461                 return i;
462             }
463             i++;
464         }
465
466         /* couldn't find specified path */
467         return -1;
(gdb) fin
Run till exit from #0  unifycr_get_fid_from_path (path=0x61d640 <targetfile> "/tmp/testfile") at ../../../../client/src/unifycr.c:463
0x0000000000408f80 in unifycr_fid_open (path=0x61d640 <targetfile> "/tmp/testfile", flags=0, mode=0, outfid=0x7ffca80e9300, outpos=0x7ffca80e9310)
    at ../../../../client/src/unifycr.c:1089
1089        int fid = unifycr_get_fid_from_path(path);
Value returned is $7 = -1
```

As above, the open fails because the `in_use` flag has been initialized to be `0`, although the entry exists.

**Comment by sandrain** [comment]
My bad. Please discard.

Long explanation:
Actually all local data structures are discarded and repopulated by reading the global meta data. I was testing with the old dev branch without merging my own PR :-(
